# Site settings
title: Fithratul Husna - WELCOME!
description: A blog is about Me, My Major and My University! WELCOME TO MY BLOG!
# baseurl: '/fithratulhusna.github.io'
# url: 'https://fithratulhusna.github.io'
# User settings
username: HELLO! WELCOME TO MY BLOG!
user_description: Iam Fithratul Husna, Student of Information System State Islamic University of Sultan Syarif Kasim Riau
user_title: FITHRATUL HUSNA
email: fitrahusna27@gmail.com
twitter_username: fithratulhusnaa
github_username:  fithratulhusna
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
