# Site settings
title: FITHRATUL HUSNA - WELCOME!
description: A blog is about Me, My Major and My University! WELCOME TO MY BLOG!
# baseurl: '/fithratulhusna.github.io'
# url: 'https://fithratulhusna.github.io'
# User settings
username: Hello!❤
user_description: Hello Welcome to My Blog!❤❤
user_title: iam FITHRATUL HUSNA <p> Student of Information System</p>
email: fitrahusna27@gmail.com
twitter_username: fithratulhusnaa
github_username:  fithratulhusna
gplus_username:  fitrahusna

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
